[package]
edition = "2021"
name = "msdsmchr"
version = "0.2.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.1"
image = "0.24.2"
reqwest = "0.11.10"
# the rayon feature is disabled because it actually makes it slower
base64 = "0.13.0"
imageproc = {version = "0.23.0", default-features = false, features = []}
oxipng = "5.0.1"
serde = {version = "1.0.137", features = ["derive"]}
serde_json = "1.0.81"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
harness = false
name = "benchmark"

[profile.release]
debug = true

# this will be removed once my prs are merged
[patch.crates-io]
imageproc = {git = "https://github.com/mat-1/imageproc"}
