name = "msdsmchr"
workers_dev = true

compatibility_date = "2022-06-22"
main = "build/worker/shim.js"

[vars]
WORKERS_RS_VERSION = "0.0.10"

[build]
# the current version of workers.rs is broken, so we use this fork
# note that to release you have to install esbuild and perl, and manually type in the command below.
# then, do wrangler publish.

# command = "cargo install --git https://github.com/mat-1/workers-rs --branch zeb/esbuild && worker-build --release"
command = ""